### ISSUE TITLE
Create Usecases

### ISSUE THREAD

**Issue by Ashkeelun** [Ashkeelun/GitHealth#11]

**Comment by Ashkeelun** [comment]
This is not finished.

**Comment by Ashkeelun** [comment]
the Background section should be removed from the usecase. Goal in context needs refinement. There is only 1 trigger, and it's not reflected in the Trigger section. There are multiple stakeholders: user, repository owner and repository facilitator (ie GitHub). Once these are complete, please let me know, and I will run through an correct the grammar.

**Comment by celalgorgun** [comment]
I added and remove some stuff. If something is not right just let me know.
