### ISSUE TITLE
No requirements.txt file for pip installation.

### ISSUE THREAD

**Issue by jakeharding** [Ashkeelun/GitHealth#16]
An established way of managing dependencies is to have a requirements.txt file created with `pip freeze > requirements.txt`.  Users can then install all dependencies in one command from a terminal with `pip install -r requirements.txt`. This works well with a virualenv, #17.

**Comment by Ashkeelun** [comment]
Thanks for the suggestion, I'll add that in.

**Comment by Ashkeelun** [comment]
A requirements.txt file has been added and installation instruction for windows have been updated.
