### ISSUE TITLE
What do the metrics mean?

### ISSUE THREAD

**Issue by jakeharding** [Ashkeelun/GitHealth#18]
After running through the setup and the suggested request in the readme, I receive this response:
```
{
    "slcSize": 18350,
    "mlcNum": 51,
    "mlcSize": 24002,
    "codeSize": 34785,
    "comtSize": 42352,
    "slcNum": 329
}
```
Did I miss the documentation describing these metrics? What do these metrics mean?

**Comment by Ashkeelun** [comment]
No, we have not made the documentation describing these metrics yet, but I agree that it should be added.
to answer your question.
slc = single line comment
mlc = multi-line comment
comt = all comment types
code = all non-comment source code
size = number of characters found
num = number of individual comments found

**Comment by Ashkeelun** [comment]
Metric Description has been added to the readme.md
